version: '3'
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        restart: always
        ports:
            - "1435:1433"
    
    mc2:
        restart: always
        build:
            context: ./
            dockerfile: ./Mc2.CrudTest.Presentation/Server/Dockerfile
        environment:
            - ASPNETCORE_URLS=http://+:5000      
        ports:
            - 8008:5000
        depends_on:
            - db