resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: npgsqlconnection-env
  literals:
    - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    - POSTGRES_USER=postgres
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=NpgsqlConnection

secretGenerator:
- name: npgsqlconnection-secrets
  envs:
  - .npgsqlconnection.secrets
