// <auto-generated />
using System;
using Mc2.CrudTest.Presentation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mc2.CrudTest.Presentation.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240603132302_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mc2.CrudTest.Presentation.Shared.Events.EventBase", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("event_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasDiscriminator<string>("event_type").HasValue("EventBase");

                   // b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mc2.CrudTest.Presentation.Shared.Events.CustomerCreatedEvent", b =>
                {
                    b.HasBaseType("Mc2.CrudTest.Presentation.Shared.Events.EventBase");

                    b.HasDiscriminator().HasValue("customer_create");
                });

            modelBuilder.Entity("Mc2.CrudTest.Presentation.Shared.Events.CustomerDeletedEvent", b =>
                {
                    b.HasBaseType("Mc2.CrudTest.Presentation.Shared.Events.EventBase");

                    b.HasDiscriminator().HasValue("customer_delete");
                });

            modelBuilder.Entity("Mc2.CrudTest.Presentation.Shared.Events.CustomerUpdatedEvent", b =>
                {
                    b.HasBaseType("Mc2.CrudTest.Presentation.Shared.Events.EventBase");

                    b.HasDiscriminator().HasValue("customer_update");
                });
#pragma warning restore 612, 618
        }
    }
}
